apiVersion: v1
kind: Namespace
metadata:
  name: auto

---
apiVersion: v1
kind: Pod
metadata:
  name: app-auto
  namespace: auto
  labels:
    app: app-auto
    owner: wangxc
  annotations:
    url: www.zhzhdwy.com
spec:
  containers:
  - image: ikubernetes/myapp:v1
    name: myapp
    ports:
    - containerPort: 80
      name: http
    livenessProbe:
      tcpSocket:
        port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-auto
  namespace: auto
  labels:
    app: app-auto
    owner: wangxc
  annotations:
    url: www.zhzhdwy.com
spec:
  selector:
    app: app-auto
    owner: wangxc
  ports:
  - port: 8080
    name: http
    targetPort: 80
