apiVersion: v1
kind: Namespace
metadata:
  name: deploy

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deploy
  namespace: deploy
spec:
  selector:
    matchLabels:
      app: app-deploy
      owner: wangxc
  replicas: 5
  template:
    metadata:
      namespace: deploy
      labels:
        app: app-deploy
        owner: wangxc
      annotations:
        url: zhzhdwy.com
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
  
---

apiVersion: v1
kind: Service
metadata:
  name: app-deploy
  namespace: deploy
spec:
  selector:
    app: app-deploy
    owner: wangxc
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
